

llm:
  model_name: gpt2
  max_length: 100

rl:
  policy: MlpPolicy
  learning_rate: 0.0003
  gamma: 0.95
  total_timesteps: 10000

training:
  batch_size: 64
  seed: 42

data:
  threshold: 4
  movielens_path: data/movielens_sample.csv
  amazon_path: data/amazon_books_sample.csv
